#!/bin/bash

python manage.py collectstatic --no-input && python manage.py makemigrations main && python manage.py migrate && gunicorn $app.wsgi:application --bind 0.0.0.0:8000 --log-level=debug --timeout 180  --workers 4

